#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${1:-enterprise-evidence}"
mkdir -p "$OUT"

{
  printf 'generated_utc=%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf 'git_head=%s\n' "$(git rev-parse HEAD 2>/dev/null || printf unknown)"
  printf 'git_branch=%s\n' "$(git branch --show-current 2>/dev/null || printf unknown)"
  printf '\n[tool versions]\n'
  rustc --version
  cargo --version
  cargo audit --version 2>/dev/null || true
  cargo deny --version 2>/dev/null || true
  gitleaks version 2>/dev/null || true
  semgrep --version 2>/dev/null || true
  syft version 2>/dev/null | head -20 || true
  cosign version 2>/dev/null | head -20 || true
  printf '\n[git status]\n'
  git status --short
} > "$OUT/build-metadata.txt"

cargo metadata --locked --format-version 1 > "$OUT/cargo-metadata.json"
cargo tree --locked > "$OUT/cargo-tree.txt"
sha256sum \
  Cargo.lock \
  Cargo.toml \
  deny.toml \
  .semgrep.yml \
  scripts/enterprise-audit.sh \
  scripts/release-evidence.sh \
  scripts/verify-repo-controls.sh \
  scripts/verify-egress-guard.sh \
  SECURITY.md \
  docs/enterprise/AUDIT_SUMMARY.md \
  docs/enterprise/EVIDENCE_HANDLING.md \
  docs/enterprise/NETWORK_EGRESS_POLICY.md \
  docs/enterprise/NO_TELEMETRY_POSITION.md \
  docs/enterprise/README.md \
  docs/enterprise/REPOSITORY_CONTROLS.md \
  docs/enterprise/ROLL_OUT_SECURITY_REVIEW.md \
  docs/enterprise/VERIFICATION_RUNBOOK.md \
  > "$OUT/source-control-sha256.txt"

if command -v cargo-audit >/dev/null 2>&1; then
  cargo audit --deny warnings > "$OUT/cargo-audit.txt" 2>&1
fi

if command -v cargo-deny >/dev/null 2>&1; then
  cargo deny check advisories bans sources > "$OUT/cargo-deny.txt" 2>&1
fi

if command -v gitleaks >/dev/null 2>&1; then
  gitleaks dir . --redact --no-banner > "$OUT/gitleaks-dir.txt" 2>&1
fi

if command -v semgrep >/dev/null 2>&1; then
  semgrep scan --config .semgrep.yml --error > "$OUT/semgrep.txt" 2>&1
fi

if [ -x target/release/rtk ]; then
  sha256sum target/release/rtk > "$OUT/rtk-release-sha256.txt"
fi

if command -v syft >/dev/null 2>&1; then
  syft dir:. --exclude './.git/**' --exclude './target/**' --exclude "./$OUT/**" -o spdx-json="$OUT/sbom.spdx.json"
fi

cat > "$OUT/README.md" <<'EOM'
# RTK Enterprise Evidence Bundle

This bundle is generated by `scripts/release-evidence.sh`.

Expected contents:
- `build-metadata.txt`: build timestamp, git status, and tool versions
- `cargo-metadata.json`: locked dependency metadata
- `cargo-tree.txt`: locked dependency tree
- `cargo-audit.txt`: RustSec advisory scan output when `cargo-audit` is installed
- `cargo-deny.txt`: dependency policy output when `cargo-deny` is installed
- `gitleaks-dir.txt`: current-tree secret scan output when `gitleaks` is installed
- `semgrep.txt`: SAST output when `semgrep` is installed
- `source-control-sha256.txt`: hashes of security-control inputs
- `rtk-release-sha256.txt`: release binary hash when `target/release/rtk` exists
- `sbom.spdx.json`: SPDX SBOM when `syft` is installed
- `repository-controls.txt`: optional hosted repository control check, generated separately with `scripts/verify-repo-controls.sh`

Run `scripts/enterprise-audit.sh` from the repository root before accepting this bundle.
EOM

printf 'Evidence written to %s\n' "$OUT"
